name = "Test"
author = "NLKoen"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fa752ef5844322c3943603bcc7afaf5f4641cc32a952b5fdac98dc07854788f"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
