name = "Project SkyHigh"
author = "NLKoen"
version = "0.0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1f7917f3f6240587375b44a9bd9815cac0fcc1c739d6681872ae4923cf985ec"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
