name = "Test"
author = "NLKoen"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47d68febb241b7a4806e33915d1058465423199c186892144b6a81fb4df8b010"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1-beta.1"
