name = "Test"
author = "NLKoen"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce28a683dc302974d69c31aaf4bb758dd08331bf3407342f58434b5350b89860"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
