name = "Test"
author = "NLKoen"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "320d4c8919df24a8bfb0927ab68c983ca6839c08b561ae24bfd0e0e783e62179"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
