name = "Test"
author = "NLKoen"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fec68d53f8b1df22c98ded9a64902947be9196d4b67d746e9f532f67d2d792ef"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1-beta.1"
