name = "Test"
author = "NLKoen"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8df4415bbb5b4efecb5a3d6043383bf8f955fa21bdb6d2c4b7a513ef2bb2b46"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
